topic_synchronizer:
  ros__parameters:
    # Modalit√† timestamp: "now" (tempo corrente) o "relative" (partendo da 0 all'arrivo del primo msg)
    timestamp_mode: "now"
    
    topic_names: ["/lidar_points", "/imu/data", "/clusters"]
    # Tipi di topic corrispondenti: "pcl" (PointCloud2), "imu" (Imu), "marker" (Marker)
    topic_types: ["pcl", "imu", "marker"]
    # Fattore di downsampling: 1 = pubblica tutti, 2 = uno ogni 2, 3 = uno ogni 3, ecc.
    downsampling_factors: [1, 1, 1]

    # $ ros2 launch hesai_ros_driver hesai.launch.py & ros2 bag play ~/ros2_ws/bags/rosbag2_2025_11_18-16_53_08-5c-0.95/ --topics /imu/data && fg
