topic_synchronizer:
  ros__parameters:
    # Modalit√† timestamp: "now" (tempo corrente) o "relative" (partendo da 0 all'arrivo del primo msg)
    timestamp_mode: "relative"
    
    topic_names: ["/lidar_points", "/lidar_imu", "clusters"]
    # Tipi di topic corrispondenti: "pcl" (PointCloud2), "imu" (Imu), "marker" (Marker)
    topic_types: ["pcl", "imu", "marker"]
    # Fattore di downsampling: 1 = pubblica tutti, 2 = uno ogni 2, 3 = uno ogni 3, ecc.
    downsampling_factors: [1, 1, 1]
